spring:
  # 数据库连接信息
  datasource:
    # 驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接的url
    url: jdbc:mysql://localhost:3306/tlias
    # 连接数据库的用户名
    username: root
    # 连接数据库的密码
    password: 3091

  # 文件上传的配置
  servlet:
    multipart:
      # 配置单个文件上传大小限制
      max-file-size: 10MB
      # 配置单个请求最大大小的限制（一次请求中可以上传多个文件）
      max-request-size: 100MB

# Mybatis配置
mybatis:
  configuration:
    # 配置mybatis的日志，指定输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启mybatis的驼峰命名自动映射开关
    map-underscore-to-camel-case: true

# 阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: web-sh-ti